import { db, ref, get, set, push, remove, onValue, runTransaction, query, limitToLast } from "./firebase.js";
import { TOPICS } from "./topics.js";
import { $, esc, toast, pid, getName, setName, buildPoints, patch } from "./common.js";
import { generate } from "./ai.js";
let custom = null;
let cache = null;
let seq = 0;
let tm;
let busy = false;
let warned = false;
$("#name").value = getName();

const hiddenIds = () => {
    try {
        return new Set(JSON.parse(localStorage.getItem("podium_hidden") || "[]"));
    }
    catch (e) {
        return new Set();
    }
};

function hideList(id) {
    const hid = hiddenIds();
    hid.add(id);
    try {
        localStorage.setItem("podium_hidden", JSON.stringify([...hid].slice(-500)));
    }
    catch (e) {
        console.warn("Could not remember hidden lists:", e);
    }
    search();
}

function unhideList(id) {
    const hid = hiddenIds();
    hid.delete(id);
    try {
        localStorage.setItem("podium_hidden", JSON.stringify([...hid]));
    }
    catch (e) {
        console.warn("Could not update hidden lists:", e);
    }
    search();
}

const recent = () => {
    try {
        return JSON.parse(localStorage.getItem("podium_recent") || "[]");
    }
    catch (e) {
        return [];
    }
};

const saveRecent = l => localStorage.setItem("podium_recent", JSON.stringify(l.slice(0, 10)));

function remember(c) {
    const l = recent().filter(x => !(x.title === c.title && x.size === c.size));
    l.unshift({
        title: c.title,
        size: c.size,
        items: c.items,
        by: c.by
    });
    saveRecent(l);
}

function showRecent() {
    const l = recent();
    $("#recent").innerHTML = l.length ? `<label>Recently played</label><ul class="plist results">` + l.map((x, i) => `<li><span>${esc(x.title)} <small>top ${x.size}</small></span><span class="acts"><button class="alt" data-r="${i}">Use</button> <button class="alt" data-x="${i}" aria-label="Remove">×</button></span></li>`).join("") + "</ul>" : "";
}

$("#recent").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    const l = recent();
    if (b.dataset.r !== undefined) {
        setCustom(l[+b.dataset.r]);
    } else {
        l.splice(+b.dataset.x, 1);
        saveRecent(l);
        showRecent();
    }
};

function setCustom(c) {
    custom = c;
    $("#picked").hidden = !c;
    $("#finder").hidden = !!c;
    $("#create").disabled = !c;
    $("#pnote").hidden = !c || !String(c.by).startsWith("AI");
    if (c) {
        $("#pnote").textContent = c.by === "AI" ? "Generated by gemini from web search. Rankings can possibly be wrong, dont blame me." : "Generated by gemini from its own memory, without web search. Rankings can be outdated or wrong, dont blame me.";
        $("#pickedname").textContent = `${c.title} · top ${c.size} · by ${c.by}`;
        custVals = null;
        if (pmode === "custom") {
            pmode = "lin";
        }
        renderSetup();
    }
}

let isPublic = true;
let nearOn = true;
let tsel = "5";
let pmode = "lin";
let custVals = null;
const nOf = () => custom ? custom.size : 10;
const whole = (s, lo, hi) => /^\d+$/.test(String(s).trim()) && +s >= lo && +s <= hi;

function renderSetup() {
    for (const b of $("#tseg").children) {
        b.classList.toggle("on", b.dataset.t === tsel);
    }
    $("#tcwrap").hidden = tsel !== "c";
    for (const b of $("#pseg").children) {
        b.classList.toggle("on", b.dataset.p === pmode);
    }
    const cu = pmode === "custom";
    const n = nOf();
    $("#pcustom").hidden = !cu;
    if (cu) {
        if (!custVals || custVals.length !== n) {
            custVals = buildPoints("lin", n).map(String);
        }
        $("#pcustom").innerHTML = custVals.map((v, i) => `<label>#${i + 1}<input type="number" min="0" max="999" step="1" value="${esc(v)}" data-i="${i}"></label>`).join("");
        $("#ppreview").textContent = "Set the points for each rank (0 to 999).";
    } else {
        $("#ppreview").textContent = `Rank 1 to ${n}: ${buildPoints(pmode, n).join(", ")}`;
    }
}

$("#tseg").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    tsel = b.dataset.t;
    renderSetup();
};

$("#pseg").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    if (b.dataset.p === "custom" && pmode !== "custom" && !custVals) {
        custVals = buildPoints(pmode, nOf()).map(String);
    }
    pmode = b.dataset.p;
    renderSetup();
};

$("#vseg").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    isPublic = b.dataset.v === "pub";
    for (const x of $("#vseg").children) {
        x.classList.toggle("on", x === b);
    }
    $("#vnote").textContent = isPublic ? "Listed on the home page, anyone can join until the game starts." : "Hidden from the home page. Only people with the room code can join.";
};

$("#pcustom").oninput = e => {
    const i = e.target.dataset.i;
    if (i !== undefined && custVals) {
        custVals[+i] = e.target.value;
    }
};

function readSetup() {
    const m = tsel === "c" ? $("#tcustom").value : tsel;
    if (!whole(m, 3, 60)) {
        toast("Custom timer must be a whole number from 3 to 60 minutes");
        return null;
    }
    let pts;
    if (pmode === "custom") {
        pts = [];
        for (let i = 0; i < custom.size; i++) {
            const s = String((custVals || [])[i] ?? "").trim();
            if (!whole(s, 0, 999)) {
                toast(`Rank #${i + 1} needs a whole number of points from 0 to 999`);
                return null;
            }
            pts.push(+s);
        }
    } else {
        pts = buildPoints(pmode, custom.size);
    }
    const hm = $("#hmax").value;
    const hc = $("#hcost").value;
    if (!whole(hm, 0, 10)) {
        toast("Hints per player must be a whole number from 0 to 10");
        return null;
    }
    if (!whole(hc, 0, 999)) {
        toast("Hint cost must be a whole number from 0 to 999");
        return null;
    }
    return {
        duration: +m * 60000,
        points: pts,
        pmode,
        hintMax: +hm,
        hintCost: +hc,
        near: nearOn
    };
}

$("#nseg").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    nearOn = b.dataset.n === "1";
    for (const x of $("#nseg").children) {
        x.classList.toggle("on", x === b);
    }
};

$("#rand").onclick = async () => {
    if (busy) {
        return;
    }
    const size = +$("#gsize").dataset.v;
    const lib = await getLib();
    const used = new Set(lib.filter(l => l.size === size).map(l => l.titleLower));
    let seen = [];
    try {
        seen = JSON.parse(localStorage.getItem("podium_rand") || "[]");
    }
    catch (e) { }
    let pool = TOPICS.filter(t => !used.has(t.toLowerCase()) && !seen.includes(t));
    if (!pool.length) {
        seen = [];
        pool = TOPICS.filter(t => !used.has(t.toLowerCase()));
    }
    if (!pool.length) {
        pool = TOPICS;
    }
    const t = pool[Math.random() * pool.length | 0];
    try {
        localStorage.setItem("podium_rand", JSON.stringify([...seen, t].slice(-80)));
    }
    catch (e) { }
    $("#q").value = t;
    search();
};

$("#clear").onclick = () => {
    setCustom(null);
    cache = null;
    showRecent();
    search();
};

let cacheAt = 0;

async function library() {
    if (!cache) {
        const v = (await get(query(ref(db, "lists"), limitToLast(300)))).val() || {};
        cache = Object.entries(v).map(([id, l]) => ({
            id,
            ...l
        })).sort((a, b) => b.created - a.created);
        cacheAt = Date.now();
    }
    return cache;
}

async function getLib() {
    try {
        return await library();
    }
    catch (e) {
        if (!warned) {
            warned = true;
            toast(e.code === "PERMISSION_DENIED" ? "The database rules block reading lists. Publish the updated rules." : "Could not load saved lists: " + e.message);
        }
        return [];
    }
}

const isAI = l => String(l.by).startsWith("AI");
const stem = w => w.length > 3 ? w.replace(/(es|s)$/, "") : w;
const words = s => s.toLowerCase().split(/\s+/).filter(Boolean).map(stem);
const titleHas = (l, ws) => ws.every(w => (l.titleLower || String(l.title).toLowerCase()).includes(w));
const byOf = l => isAI(l) ? "AI" : l.by;

async function share(c) {
    try {
        const key = c.title.toLowerCase();
        const lib = await getLib();
        const dup = lib.find(l => l.titleLower === key && l.size === c.size);
        if (dup) {
            c.id = dup.id;
            return;
        }
        const items = c.items.map(i => ({
            n: i.n,
            a: i.a || []
        }));
        const created = Date.now();
        const r = await push(ref(db, "lists"), {
            title: c.title,
            titleLower: key,
            size: c.size,
            items,
            by: c.by,
            created
        });
        c.id = r.key;
        if (cache) {
            cache.unshift({
                id: r.key,
                title: c.title,
                titleLower: key,
                size: c.size,
                items,
                by: c.by,
                created
            });
        }
    }
    catch (e) {
        console.warn("Could not share the generated list:", e);
    }
}

let showHid = false;

async function search() {
    if (busy) {
        return;
    }
    const my = ++seq;
    const raw = $("#q").value.trim();
    const size = +$("#gsize").dataset.v;
    const lib = await getLib();
    if (my !== seq) {
        return;
    }
    $("#browse").textContent = lib.length ? `Browse saved lists (${lib.length})` : "Browse saved lists";
    const exact = raw.length >= 3 ? lib.find(l => l.titleLower === raw.toLowerCase() && l.size === size) : null;
    $("#qgo").textContent = exact ? "Use saved list" : "Create";
    let rows = [];
    let hidN = 0;
    if (raw.length >= 2) {
        const ws = words(raw);
        const hid = hiddenIds();
        for (const l of lib) {
            if (!titleHas(l, ws)) {
                continue;
            }
            const isHid = hid.has(l.id) && l !== exact;
            if (isHid) {
                hidN++;
                if (!showHid) {
                    continue;
                }
            }
            rows.push([l, isHid]);
        }
        rows.sort((a, b) => (b[0] === exact) - (a[0] === exact));
        rows = rows.slice(0, 3);
    }
    const h = rows.length ? [`<li><span class="mute">${exact ? "Already saved with this size:" : "Already saved, check before creating:"}</span></li>`] : [];
    for (const [l, isHid] of rows) {
        const side = l === exact ? "" : isHid ? ` <button class="alt" data-unhide="${esc(l.id)}">Unhide</button>` : ` <button class="alt" data-hide="${esc(l.id)}" aria-label="Hide this suggestion" title="Hide this suggestion">×</button>`;
        h.push(`<li><span>${esc(l.title)} <small>top ${l.size} · ${esc(byOf(l))}</small></span><span class="acts"><button class="alt" data-id="${esc(l.id)}">Use</button>${side}</span></li>`);
    }
    if (exact) {
        h.push(`<li><span class="mute">Want a fresh version anyway?</span><span class="acts"><button class="alt" data-force="1">Create anyway</button></span></li>`);
    }
    patch($("#results"), h);
    $("#hidnote").hidden = !hidN && !showHid;
    $("#showhid").textContent = showHid ? "Stop showing hidden lists" : `Show hidden (${hidN})`;
}

async function create(force) {
    if (busy) {
        return;
    }
    const topic = $("#q").value.trim();
    const size = +$("#gsize").dataset.v;
    if (topic.length < 3) {
        return toast("Type at least 3 characters for the list title");
    }
    const lib = await getLib();
    if (!force) {
        const hit = lib.find(l => l.titleLower === topic.toLowerCase() && l.size === size);
        if (hit) {
            setCustom(hit);
            patch($("#results"), []);
            return;
        }
    }
    busy = true;
    seq++;
    $("#qgo").disabled = true;
    patch($("#results"), [`<li><span class="mute">Asking Gemini for the top ${size}…</span></li>`]);
    try {
        const c = await generate(topic, size);
        setCustom(c);
        patch($("#results"), []);
        share(c);
    }
    catch (err) {
        toast(err.message);
        busy = false;
        search();
    }
    busy = false;
    $("#qgo").disabled = false;
}

$("#results").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    if (b.dataset.force) {
        create(true);
    } else if (b.dataset.hide) {
        hideList(b.dataset.hide);
    } else if (b.dataset.unhide) {
        unhideList(b.dataset.unhide);
    } else if (b.dataset.id) {
        const l = (cache || []).find(x => x.id === b.dataset.id);
        if (l) {
            setCustom(l);
            patch($("#results"), []);
        }
    }
};

$("#showhid").onclick = e => {
    e.preventDefault();
    showHid = !showHid;
    search();
};

$("#qgo").onclick = () => create(false);

$("#q").onkeydown = e => {
    if (e.key === "Enter") {
        e.preventDefault();
    }
};

$("#q").oninput = () => {
    clearTimeout(tm);
    tm = setTimeout(search, 150);
};

$("#gsize").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    $("#gsize").dataset.v = b.dataset.v;
    for (const x of $("#gsize").children) {
        x.classList.toggle("on", x === b);
    }
    search();
};

const pk = {
    q: "",
    size: "all",
    src: "all",
    sort: "new"
};
let pkOpen = false;

function pkDraw() {
    const lib = cache || [];
    const ws = words(pk.q);
    const rows = lib.filter(l => (pk.size === "all" || l.size === +pk.size) && (pk.src === "all" || (pk.src === "ai") === isAI(l)) && titleHas(l, ws));
    rows.sort(pk.sort === "az" ? (a, b) => String(a.title).localeCompare(String(b.title)) : (a, b) => (b.created || 0) - (a.created || 0));
    const h = rows.map(l => `<li><span>${esc(l.title)} <small>top ${l.size} · ${esc(byOf(l))}</small></span><span class="acts"><button class="alt" data-id="${esc(l.id)}">Use</button></span></li>`);
    patch($("#pklist"), h.length ? h : [`<li><span class="mute">${lib.length ? "No lists match" : "No saved lists yet"}</span></li>`]);
    $("#pkcount").textContent = `${rows.length} of ${lib.length} lists${lib.length >= 300 ? " (newest 300 only)" : ""}`;
    $("#pkclear").hidden = !(pk.q || pk.size !== "all" || pk.src !== "all");
}

function pkSync() {
    for (const b of $("#pksize").children) {
        b.classList.toggle("on", b.dataset.z === pk.size);
    }
    for (const b of $("#pksrc").children) {
        b.classList.toggle("on", b.dataset.s === pk.src);
    }
    $("#pkq").value = pk.q;
    $("#pksort").dataset.v = pk.sort;
    for (const b of $("#pksort").children) {
        b.classList.toggle("on", b.dataset.v === pk.sort);
    }
}

function pkChange() {
    pkSync();
    pkDraw();
    $("#pklist").scrollTop = 0;
}

async function openPicker() {
    if (pkOpen) {
        return;
    }
    pkOpen = true;
    $("#picker").hidden = false;
    document.body.style.overflow = "hidden";
    history.pushState({ pk: 1 }, "");
    if (cache && Date.now() - cacheAt > 60000) {
        cache = null;
    }
    pkSync();
    if (!cache) {
        patch($("#pklist"), [`<li><span class="mute">Loading saved lists…</span></li>`]);
    }
    await getLib();
    if (pkOpen) {
        pkDraw();
    }
}

function hidePicker() {
    if (!pkOpen) {
        return;
    }
    pkOpen = false;
    $("#picker").hidden = true;
    document.body.style.overflow = "";
}

function closePicker() {
    if (!pkOpen) {
        return;
    }
    if (history.state && history.state.pk) {
        history.back();
    } else {
        hidePicker();
    }
}

window.addEventListener("popstate", hidePicker);

document.addEventListener("keydown", e => {
    if (e.key === "Escape") {
        closePicker();
    }
});

$("#browse").onclick = openPicker;
$("#pkclose").onclick = closePicker;

$("#pkq").oninput = () => {
    pk.q = $("#pkq").value.trim();
    pkDraw();
    $("#pklist").scrollTop = 0;
};

$("#pksize").onclick = e => {
    const b = e.target.closest("button");
    if (b) {
        pk.size = b.dataset.z;
        pkChange();
    }
};

$("#pksrc").onclick = e => {
    const b = e.target.closest("button");
    if (b) {
        pk.src = b.dataset.s;
        pkChange();
    }
};

$("#pksort").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    pk.sort = b.dataset.v;
    pkChange();
};

$("#pkclear").onclick = () => {
    pk.q = "";
    pk.size = "all";
    pk.src = "all";
    pkChange();
};

$("#pklist").onclick = e => {
    const b = e.target.closest("button");
    if (!b || !b.dataset.id) {
        return;
    }
    const l = (cache || []).find(x => x.id === b.dataset.id);
    if (l) {
        setCustom(l);
        closePicker();
    }
};

showRecent();
const listId = new URLSearchParams(location.search).get("list");

if (listId) {
    get(ref(db, "lists/" + listId)).then(s => {
        const v = s.val();
        if (v) {
            setCustom({
                id: listId,
                ...v
            });
        } else {
            search();
        }
    }).catch(() => {
        toast("Could not load that list");
        search();
    });
} else {
    search();
}

const name = () => {
    const n = $("#name").value.trim();
    if (!n) {
        toast("Enter your name first");
        return null;
    }
    setName(n);
    return n;
};

const gen = () => Array.from({ length: 4 }, () => "ABCDEFGHJKLMNPQRSTUVWXYZ"[Math.random() * 24 | 0]).join("");

async function add(c, n) {
    const res = await runTransaction(ref(db, `rooms/${c}/players`), p => {
        p = p || {};
        if (p[pid]) {
            return p;
        }
        if (Object.keys(p).length >= 10) {
            return;
        }
        p[pid] = {
            name: n,
            score: 0,
            hints: 0,
            active: true,
            online: true
        };
        return p;
    });
    return res.committed;
}

$("#create").onclick = async () => {
    if (!custom) {
        return toast("Pick a list first");
    }
    const n = name();
    if (!n) {
        return;
    }
    const cfg = readSetup();
    if (!cfg) {
        return;
    }
    const topic = custom.title;
    const size = custom.size;
    const items = custom.items.map(i => ({
        n: i.n,
        a: i.a || []
    }));
    const created = Date.now();
    for (let k = 0; k < 6; k++) {
        const c = gen();
        const r = await runTransaction(ref(db, "rooms/" + c), x => x ? undefined : {
            host: pid,
            status: "lobby",
            topic,
            size,
            items,
            ...cfg,
            public: isPublic,
            created
        });
        if (r.committed) {
            remember(custom);
            await add(c, n);
            if (isPublic) {
                try {
                    await set(ref(db, "publicRooms/" + c), {
                        topic,
                        size,
                        by: n,
                        n: 1,
                        created,
                        ts: Date.now()
                    });
                }
                catch (e) {
                    console.warn("Could not list the room publicly:", e);
                }
            }
            location.href = "lobby.html?room=" + c;
            return;
        }
    }
    toast("Could not create a room, try again");
};

const dest = r => (r.status === "lobby" ? "lobby" : r.status === "playing" ? "game" : "results") + ".html?room=";

async function watch(c, n) {
    const res = await runTransaction(ref(db, `rooms/${c}/spectators`), p => {
        p = p || {};
        if (p[pid]) {
            p[pid].name = n;
            p[pid].online = true;
            return p;
        }
        if (Object.keys(p).length >= 30) {
            return;
        }
        p[pid] = {
            name: n,
            online: true
        };
        return p;
    });
    return res.committed;
}

async function joinRoom(c) {
    const n = name();
    if (!n) {
        return;
    }
    if (c.length !== 4) {
        return toast("Room codes have 4 letters");
    }
    const r = (await get(ref(db, "rooms/" + c))).val();
    if (!r) {
        return toast("Room not found");
    }
    const mine = r.players && r.players[pid];
    if (r.status !== "lobby" && !mine) {
        return toast("That game already started");
    }
    if (!mine && !(await add(c, n))) {
        return toast("Room is full");
    }
    location.href = dest(r) + c;
}

$("#join").onclick = () => joinRoom($("#joincode").value.trim().toUpperCase());

$("#pubrooms").onclick = e => {
    const b = e.target.closest("button");
    if (b && b.dataset.j && !b.disabled) {
        joinRoom(b.dataset.j);
    } else if (b && b.dataset.s) {
        spectateRoom(b.dataset.s);
    }
};

let pub = {};
const purged = new Set();
const verdict = {};
const checking = new Set();

async function verify(keys) {
    await Promise.all(keys.map(async k => {
        checking.add(k);
        try {
            const st = (await get(ref(db, `rooms/${k}/status`))).val();
            verdict[k] = { ok: st === "lobby", at: Date.now() };
            if (st !== "lobby") {
                remove(ref(db, "publicRooms/" + k)).catch(() => { });
            }
        }
        catch (e) {
            verdict[k] = { ok: true, at: Date.now() };
        }
        checking.delete(k);
    }));
    drawPub();
}

function drawPub() {
    const now = Date.now();
    const rows = Object.entries(pub).filter(([k, v]) => {
        if (!v || !v.topic) {
            return false;
        }
        if (now - v.ts > 600000 && !purged.has(k)) {
            purged.add(k);
            remove(ref(db, "publicRooms/" + k)).catch(() => { });
        }
        return now - v.ts < 180000;
    }).sort((a, b) => (b[1].created || 0) - (a[1].created || 0) || (a[0] < b[0] ? -1 : 1)).slice(0, 12);
    const need = rows.map(([k]) => k).filter(k => !checking.has(k) && (!verdict[k] || Date.now() - verdict[k].at > 20000));
    if (need.length) {
        verify(need);
    }
    const shown = rows.filter(([k]) => verdict[k] && verdict[k].ok);
    const h = shown.map(([k, v]) => {
        const full = v.n >= 10;
        return `<li><span>${esc(v.topic)} <small>top ${v.size} · ${esc(k)} · host ${esc(v.by)} · ${v.n}/10</small></span><span class="acts"><button class="alt" data-j="${esc(k)}"${full ? " disabled" : ""}>${full ? "Full" : "Join"}</button><button class="alt" data-s="${esc(k)}">Spectate</button></span></li>`;
    });
    patch($("#pubrooms"), h.length ? h : [`<li><span class="mute">No public rooms right now</span></li>`]);
}

onValue(ref(db, "publicRooms"), s => {
    pub = s.val() || {};
    drawPub();
}, e => {
    console.warn("Could not read public rooms:", e);
});

setInterval(drawPub, 15000);

async function spectateRoom(c) {
    const n = name();
    if (!n) {
        return;
    }
    if (c.length !== 4) {
        return toast("Room codes have 4 letters");
    }
    const r = (await get(ref(db, "rooms/" + c))).val();
    if (!r) {
        return toast("Room not found");
    }
    if (!(r.players && r.players[pid]) && !(await watch(c, n))) {
        return toast("Too many spectators in that room");
    }
    location.href = dest(r) + c;
}

$("#spectate").onclick = () => spectateRoom($("#joincode").value.trim().toUpperCase());