import { db, ref, get, push, runTransaction, query, limitToLast } from "./firebase.js";
import { $, esc, toast, pid, getName, setName, buildPoints } from "./common.js";
import { generate } from "./ai.js";
let custom = null;
let cache = null;
let seq = 0;
let tm;
let busy = false;
let warned = false;
let view = null;
let viewSrc = null;
let viewLen = -1;
let viewHid = "";
$("#name").value = getName();

const hiddenIds = () => {
    try {
        return new Set(JSON.parse(localStorage.getItem("podium_hidden") || "[]"));
    }
    catch (e) {
        return new Set();
    }
};

function visibleLib(lib) {
    const hid = hiddenIds();
    const sig = [...hid].join(",");
    if (view && viewSrc === lib && viewLen === lib.length && viewHid === sig) {
        return view;
    }
    view = lib.filter(l => !hid.has(l.id));
    viewSrc = lib;
    viewLen = lib.length;
    viewHid = sig;
    return view;
}

function hideList(id) {
    const hid = hiddenIds();
    hid.add(id);
    try {
        localStorage.setItem("podium_hidden", JSON.stringify([...hid].slice(-500)));
    }
    catch (e) {
        console.warn("Could not remember hidden lists:", e);
    }
    search();
}

const recent = () => {
    try {
        return JSON.parse(localStorage.getItem("podium_recent") || "[]");
    }
    catch (e) {
        return [];
    }
};

const saveRecent = l => localStorage.setItem("podium_recent", JSON.stringify(l.slice(0, 10)));

function remember(c) {
    const l = recent().filter(x => !(x.title === c.title && x.size === c.size));
    l.unshift({
        title: c.title,
        size: c.size,
        items: c.items,
        by: c.by
    });
    saveRecent(l);
}

function showRecent() {
    const l = recent();
    $("#recent").innerHTML = l.length ? `<label>Recently played</label><ul class="plist results">` + l.map((x, i) => `<li><span>${esc(x.title)} <small>top ${x.size}</small></span><span class="acts"><button class="alt" data-r="${i}">Use</button> <button class="alt" data-x="${i}" aria-label="Remove">×</button></span></li>`).join("") + "</ul>" : "";
}

$("#recent").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    const l = recent();
    if (b.dataset.r !== undefined) {
        setCustom(l[+b.dataset.r]);
    } else {
        l.splice(+b.dataset.x, 1);
        saveRecent(l);
        showRecent();
    }
};

function setCustom(c) {
    custom = c;
    $("#picked").hidden = !c;
    $("#finder").hidden = !!c;
    $("#create").disabled = !c;
    $("#pnote").hidden = !c || !String(c.by).startsWith("AI");
    if (c) {
        $("#pnote").textContent = c.by === "AI" ? "Generated by gemini from web search. Rankings can possibly be wrong, dont blame me." : "Generated by gemini from its own memory, without web search. Rankings can be outdated or wrong, dont blame me.";
        $("#pickedname").textContent = `${c.title} · top ${c.size} · by ${c.by}`;
        custVals = null;
        if (pmode === "custom") {
            pmode = "lin";
        }
        renderSetup();
    }
}

let tsel = "5";
let pmode = "lin";
let custVals = null;
const nOf = () => custom ? custom.size : 10;
const whole = (s, lo, hi) => /^\d+$/.test(String(s).trim()) && +s >= lo && +s <= hi;

function renderSetup() {
    for (const b of $("#tseg").children) {
        b.classList.toggle("on", b.dataset.t === tsel);
    }
    $("#tcwrap").hidden = tsel !== "c";
    for (const b of $("#pseg").children) {
        b.classList.toggle("on", b.dataset.p === pmode);
    }
    const cu = pmode === "custom";
    const n = nOf();
    $("#pcustom").hidden = !cu;
    if (cu) {
        if (!custVals || custVals.length !== n) {
            custVals = buildPoints("lin", n).map(String);
        }
        $("#pcustom").innerHTML = custVals.map((v, i) => `<label>#${i + 1}<input type="number" min="0" max="999" step="1" value="${esc(v)}" data-i="${i}"></label>`).join("");
        $("#ppreview").textContent = "Set the points for each rank (0 to 999).";
    } else {
        $("#ppreview").textContent = `Rank 1 to ${n}: ${buildPoints(pmode, n).join(", ")}`;
    }
}

$("#tseg").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    tsel = b.dataset.t;
    renderSetup();
};

$("#pseg").onclick = e => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    if (b.dataset.p === "custom" && pmode !== "custom" && !custVals) {
        custVals = buildPoints(pmode, nOf()).map(String);
    }
    pmode = b.dataset.p;
    renderSetup();
};

$("#pcustom").oninput = e => {
    const i = e.target.dataset.i;
    if (i !== undefined && custVals) {
        custVals[+i] = e.target.value;
    }
};

function readSetup() {
    const m = tsel === "c" ? $("#tcustom").value : tsel;
    if (!whole(m, 3, 60)) {
        toast("Custom timer must be a whole number from 3 to 60 minutes");
        return null;
    }
    let pts;
    if (pmode === "custom") {
        pts = [];
        for (let i = 0; i < custom.size; i++) {
            const s = String((custVals || [])[i] ?? "").trim();
            if (!whole(s, 0, 999)) {
                toast(`Rank #${i + 1} needs a whole number of points from 0 to 999`);
                return null;
            }
            pts.push(+s);
        }
    } else {
        pts = buildPoints(pmode, custom.size);
    }
    const hm = $("#hmax").value;
    const hc = $("#hcost").value;
    if (!whole(hm, 0, 10)) {
        toast("Hints per player must be a whole number from 0 to 10");
        return null;
    }
    if (!whole(hc, 0, 999)) {
        toast("Hint cost must be a whole number from 0 to 999");
        return null;
    }
    return {
        duration: +m * 60000,
        points: pts,
        pmode,
        hintMax: +hm,
        hintCost: +hc
    };
}

$("#clear").onclick = () => {
    setCustom(null);
    cache = null;
    showRecent();
    search();
};

async function library() {
    if (!cache) {
        const v = (await get(query(ref(db, "lists"), limitToLast(300)))).val() || {};
        cache = Object.entries(v).map(([id, l]) => ({
            id,
            ...l
        })).sort((a, b) => b.created - a.created);
    }
    return cache;
}

let filled = null;
const isAI = l => String(l.by).startsWith("AI");

function fillSaved(lib) {
    if (filled === lib) {
        return;
    }
    filled = lib;
    const opt = l => `<option value="${esc(l.id)}">${esc(l.title)} · top ${l.size}${isAI(l) ? "" : " · " + esc(l.by)}</option>`;
    const byTitle = (a, b) => a.title.localeCompare(b.title);
    const ai = lib.filter(isAI).sort(byTitle);
    const pl = lib.filter(l => !isAI(l)).sort(byTitle);
    $("#saved").innerHTML = `<option value="">${lib.length ? `Pick a saved list (${lib.length})` : "No saved lists yet"}</option>` + (ai.length ? `<optgroup label="AI generated">${ai.map(opt).join("")}</optgroup>` : "") + (pl.length ? `<optgroup label="Made by players">${pl.map(opt).join("")}</optgroup>` : "");
}

$("#saved").onchange = () => {
    const l = (cache || []).find(x => x.id === $("#saved").value);
    if (l) {
        setCustom(l);
        $("#saved").value = "";
    }
};

async function share(c) {
    try {
        const key = c.title.toLowerCase();
        const lib = await library().catch(() => []);
        const dup = lib.find(l => l.titleLower === key && l.size === c.size);
        if (dup) {
            c.id = dup.id;
            return;
        }
        const items = c.items.map(i => ({
            n: i.n,
            a: i.a || []
        }));
        const created = Date.now();
        const r = await push(ref(db, "lists"), {
            title: c.title,
            titleLower: key,
            size: c.size,
            items,
            by: c.by,
            created
        });
        c.id = r.key;
        if (cache) {
            cache.unshift({
                id: r.key,
                title: c.title,
                titleLower: key,
                size: c.size,
                items,
                by: c.by,
                created
            });
            filled = null;
        }
    }
    catch (e) {
        console.warn("Could not share the generated list:", e);
    }
}

const stem = w => w.length > 3 ? w.replace(/(es|s)$/, "") : w;
const hay = l => l.titleLower + " " + (l.items || []).map(i => i.n.toLowerCase()).join(" ");

async function search() {
    const my = ++seq;
    const raw = $("#q").value.trim();
    const words = raw.toLowerCase().split(/\s+/).filter(Boolean);
    let lib = [];
    try {
        lib = await library();
    }
    catch (e) {
        if (!warned) {
            warned = true;
            toast(e.code === "PERMISSION_DENIED" ? "The database rules block reading lists. Publish the updated rules." : "Could not load saved lists: " + e.message);
        }
    }
    if (my !== seq) {
        return;
    }
    fillSaved(lib);
    const shown = visibleLib(lib);
    const hits = shown.filter(l => {
        const h = hay(l);
        return words.every(w => h.includes(stem(w)));
    }).slice(0, 6);
    let h = hits.map(l => `<li><span>${esc(l.title)} <small>top ${l.size} · ${esc(l.by)}</small></span><span class="acts"><button class="alt" data-id="${l.id}">Use</button> <button class="alt" data-hide="${l.id}" aria-label="Hide this list" title="Hide this list">×</button></span></li>`).join("");
    if (raw.length >= 3) {
        h += `<li><span class="mute">${hits.length ? "None of these? " : ""}Generate "${esc(raw)}" with AI</span><span>${[5, 10, 15, 20].map(n => `<button class="alt" data-gen="${n}">Top ${n}</button>`).join(" ")}</span></li>`;
    }
    if (!h) {
        h = `<li><span class="mute">Type a topic to find a saved list or generate one</span></li>`;
    }
    $("#results").innerHTML = h;
}

$("#results").onclick = async (e) => {
    const b = e.target.closest("button");
    if (!b) {
        return;
    }
    if (b.dataset.gen) {
        if (busy) {
            return;
        }
        const topic = $("#q").value.trim();
        const size = +b.dataset.gen;
        busy = true;
        seq++;
        $("#results").innerHTML = `<li><span class="mute">Asking Gemini for the top ${size}…</span></li>`;
        try {
            const c = await generate(topic, size);
            setCustom(c);
            $("#results").innerHTML = "";
            share(c);
        }
        catch (err) {
            toast(err.message);
            search();
        }
        busy = false;
        return;
    }
    if (b.dataset.hide) {
        hideList(b.dataset.hide);
        return;
    }
    const l = (cache || []).find(x => x.id === b.dataset.id);
    if (l) {
        setCustom(l);
        $("#results").innerHTML = "";
    }
};

$("#qgo").onclick = search;

$("#q").onkeydown = e => {
    if (e.key === "Enter") {
        search();
    }
};

$("#q").oninput = () => {
    clearTimeout(tm);
    tm = setTimeout(search, 300);
};

showRecent();
const listId = new URLSearchParams(location.search).get("list");

if (listId) {
    get(ref(db, "lists/" + listId)).then(s => {
        const v = s.val();
        if (v) {
            setCustom({
                id: listId,
                ...v
            });
        } else {
            search();
        }
    }).catch(() => {
        toast("Could not load that list");
        search();
    });
} else {
    search();
}

const name = () => {
    const n = $("#name").value.trim();
    if (!n) {
        toast("Enter your name first");
        return null;
    }
    setName(n);
    return n;
};

const gen = () => Array.from({ length: 4 }, () => "ABCDEFGHJKLMNPQRSTUVWXYZ"[Math.random() * 24 | 0]).join("");

async function add(c, n) {
    const res = await runTransaction(ref(db, `rooms/${c}/players`), p => {
        p = p || {};
        if (p[pid]) {
            return p;
        }
        if (Object.keys(p).length >= 10) {
            return;
        }
        p[pid] = {
            name: n,
            score: 0,
            hints: 0,
            active: true,
            online: true
        };
        return p;
    });
    return res.committed;
}

$("#create").onclick = async () => {
    if (!custom) {
        return toast("Pick a list first");
    }
    const n = name();
    if (!n) {
        return;
    }
    const cfg = readSetup();
    if (!cfg) {
        return;
    }
    const topic = custom.title;
    const size = custom.size;
    const items = custom.items.map(i => ({
        n: i.n,
        a: i.a || []
    }));
    for (let k = 0; k < 6; k++) {
        const c = gen();
        const r = await runTransaction(ref(db, "rooms/" + c), x => x ? undefined : {
            host: pid,
            status: "lobby",
            topic,
            size,
            items,
            ...cfg,
            created: Date.now()
        });
        if (r.committed) {
            remember(custom);
            await add(c, n);
            location.href = "lobby.html?room=" + c;
            return;
        }
    }
    toast("Could not create a room, try again");
};

const dest = r => (r.status === "lobby" ? "lobby" : r.status === "playing" ? "game" : "results") + ".html?room=";

async function watch(c, n) {
    const res = await runTransaction(ref(db, `rooms/${c}/spectators`), p => {
        p = p || {};
        if (p[pid]) {
            p[pid].name = n;
            p[pid].online = true;
            return p;
        }
        if (Object.keys(p).length >= 30) {
            return;
        }
        p[pid] = {
            name: n,
            online: true
        };
        return p;
    });
    return res.committed;
}

$("#join").onclick = async () => {
    const n = name();
    if (!n) {
        return;
    }
    const c = $("#joincode").value.trim().toUpperCase();
    if (c.length !== 4) {
        return toast("Room codes have 4 letters");
    }
    const r = (await get(ref(db, "rooms/" + c))).val();
    if (!r) {
        return toast("Room not found");
    }
    const mine = r.players && r.players[pid];
    if (r.status !== "lobby" && !mine) {
        return toast("That game already started");
    }
    if (!mine && !(await add(c, n))) {
        return toast("Room is full");
    }
    location.href = dest(r) + c;
};

$("#spectate").onclick = async () => {
    const n = name();
    if (!n) {
        return;
    }
    const c = $("#joincode").value.trim().toUpperCase();
    if (c.length !== 4) {
        return toast("Room codes have 4 letters");
    }
    const r = (await get(ref(db, "rooms/" + c))).val();
    if (!r) {
        return toast("Room not found");
    }
    if (!(r.players && r.players[pid]) && !(await watch(c, n))) {
        return toast("Too many spectators in that room");
    }
    location.href = dest(r) + c;
};