export const TOPICS = [
    "Greatest footballers of all time", "Best-selling video games", "Greatest movies ever made", "Best TV series of all time",
    "Greatest rock bands", "Best-selling albums ever", "Tallest buildings in the world", "Largest countries by area",
    "Most populated cities", "Longest rivers in the world", "Highest mountains", "Greatest tennis players",
    "Greatest basketball players", "Greatest cricketers", "Best Formula 1 drivers", "Most visited tourist attractions",
    "Highest-grossing films", "Greatest novels of all time", "Greatest rappers", "Greatest guitarists",
    "Best animated films", "Best fast food chains", "Most valuable companies", "Richest people in history",
    "Greatest scientists of all time", "Most influential inventions", "Best anime series", "Best Pixar movies",
    "Greatest boxers of all time", "Best chess players ever", "Most popular programming languages", "Best smartphones ever made",
    "Greatest painters", "Greatest composers", "Best sitcoms ever", "Best horror movies",
    "Best video game consoles", "Most iconic cars", "Fastest production cars", "Largest lakes in the world",
    "Most spoken languages", "Best cuisines in the world", "Greatest Olympic athletes", "Best Marvel movies",
    "Greatest sci-fi movies", "Best fantasy book series", "Most subscribed YouTube channels", "Greatest comedians",
    "Best pop singers ever", "Greatest female artists", "Best Disney movies", "Best Nintendo games",
    "Most influential philosophers", "Greatest military leaders", "Most powerful empires", "Biggest sports stadiums",
    "Greatest football managers", "Best football clubs ever", "Best national football teams", "Greatest golfers",
    "Greatest wrestlers", "Best sneakers of all time", "Most popular board games", "Best strategy games",
    "Greatest RPG video games", "Best open-world games", "Best-selling books ever", "Greatest film directors",
    "Greatest actors of all time", "Greatest actresses of all time", "Best crime TV shows", "Best fantasy TV shows",
    "Best superhero movies", "Best war movies", "Best comedy movies", "Best 90s movies",
    "Best 80s songs", "Best 2000s songs", "Best hip-hop albums", "Best metal bands",
    "Best electronic music artists", "Best country singers", "Greatest jazz musicians", "Best K-pop groups",
    "Best Bollywood movies", "Best cartoon series", "Best Pokémon ever", "Best fighting games",
    "Best racing games", "Best horror games", "Best Zelda games", "Best Mario games",
    "Most dangerous animals", "Fastest animals", "Largest animals", "Most intelligent animals",
    "Most beautiful islands", "Best beaches in the world", "Best cities to live in", "Most beautiful countries",
    "Best theme parks", "Best national parks", "Largest deserts", "Largest oceans and seas",
    "Most famous landmarks", "Greatest wonders of the world", "Best museums in the world", "Best universities in the world",
    "Most popular sports", "Greatest rugby players", "Best baseball players", "Best NFL quarterbacks",
    "Greatest hockey players", "Best cyclists ever", "Greatest swimmers", "Best sprinters ever",
    "Greatest esports players", "Best YouTubers ever", "Most followed Instagram accounts", "Best social media apps",
    "Best coffee brands", "Best chocolate brands", "Best pizza toppings", "Best soft drinks",
    "Best breakfast foods", "Best street foods", "Best desserts", "Best sports cars brands",
    "Best luxury brands", "Best airlines in the world", "Fastest trains", "Most important battles in history",
    "Most influential leaders", "Greatest explorers", "Most famous scientists today", "Best space missions",
    "Largest planets and moons", "Most famous detectives", "Greatest fictional villains", "Greatest fictional heroes",

    // Animals
    "Most popular pets", "Most popular dog breeds", "Most popular cat breeds", "Largest land animals",
    "Largest birds", "Largest sharks", "Largest snakes", "Fastest birds",
    "Fastest fish", "Fastest land animals", "Most venomous animals", "Most dangerous sea creatures",
    "Most dangerous snakes", "Smartest dog breeds", "Biggest dog breeds", "Smallest dog breeds",
    "Cutest animals", "Rarest animals", "Most endangered animals", "Longest-living animals",
    "Heaviest animals", "Tallest animals", "Best animals for kids", "Best animal movies",
    "Best zoo animals", "Most beautiful birds", "Best-known dinosaurs", "Largest dinosaurs",
    "Deadliest animals to humans", "Largest insects", "Most colourful animals", "Strongest animals",
    "Best swimmers in the animal world", "Best jumpers in the animal world", "Most famous cartoon animals", "Best farm animals",
    "Most common animals in Africa", "Most common animals in Australia", "Best animals to see on safari", "Largest whales and dolphins",

    // Movies
    "Best Christopher Nolan movies", "Best Steven Spielberg movies", "Best Quentin Tarantino movies", "Best Martin Scorsese movies",
    "Best Stanley Kubrick movies", "Best Tim Burton movies", "Best Pixar films", "Best DreamWorks movies",
    "Best Studio Ghibli films", "Best Harry Potter movies", "Best Star Wars movies", "Best Lord of the Rings movies",
    "Best Batman movies", "Best Spider-Man movies", "Best James Bond movies", "Best Fast and Furious movies",
    "Best Marvel heroes", "Best DC superheroes", "Best Marvel villains", "Best movie villains",
    "Best movie soundtracks", "Best movie quotes", "Best movie twists", "Best movie sequels",
    "Best movie trilogies", "Best action movies", "Best romantic movies", "Best thriller movies",
    "Best sci-fi franchises", "Best zombie movies", "Best vampire movies", "Best sports movies",
    "Best musicals ever", "Best heist movies", "Best mafia movies", "Best western movies",
    "Best disaster movies", "Best 70s movies", "Best 2000s movies", "Best 2010s movies",
    "Best 2020s movies", "Best foreign-language films", "Best Korean movies", "Best Japanese movies",
    "Best British movies", "Best Indian movies", "Best Oscar-winning movies", "Best films with Oscar snubs",
    "Most rewatchable movies", "Best feel-good movies", "Best movies for kids", "Best family movies",
    "Best comedies of the 90s", "Best mind-bending movies", "Best movie monsters", "Best movie robots",
    "Best animated sequels", "Highest-grossing animated films", "Highest-grossing horror movies", "Longest movies ever made",
    "Best opening scenes in movies", "Best movie scores", "Best cinematography in movies", "Best movie car chases",

    // TV Shows
    "Best Netflix series", "Best HBO shows", "Best Disney Channel shows", "Best Nickelodeon shows",
    "Best Cartoon Network shows", "Best reality TV shows", "Best game shows", "Best talk shows",
    "Best late-night hosts", "Best sitcom characters", "Best drama series", "Best medical dramas",
    "Best legal dramas", "Best fantasy series", "Best sci-fi TV series", "Best anime of all time",
    "Best shonen anime", "Best anime movies", "Best anime openings", "Best anime characters",
    "Best anime villains", "Best British TV shows", "Best Korean dramas", "Best Spanish-language series",
    "Best miniseries", "Best TV finales", "Best TV villains", "Best TV couples",
    "Best TV theme songs", "Best kids TV shows", "Best 90s TV shows", "Best 2000s TV shows",
    "Best 2010s TV shows", "Best true crime series", "Best documentary series", "Best nature documentaries",
    "Best cooking shows", "Best animated sitcoms", "Best Adult Swim shows", "Best superhero TV shows",
    "Best spy TV shows", "Best teen shows", "Best workplace comedies", "Longest-running TV shows",
    "Most-watched TV episodes", "Best Friends characters", "Best Simpsons characters", "Best Breaking Bad characters",
    "Best Game of Thrones characters", "Best Stranger Things characters", "Best The Office characters", "Best Pokémon anime characters",

    // Actors
    "Highest-paid actors", "Best action stars", "Best comedy actors", "Best method actors",
    "Best Hollywood actors today", "Best British actors", "Best Indian actors", "Best Korean actors",
    "Best Oscar-winning actors", "Best actors of the 90s", "Best actors of the 2000s", "Best actors under 40",
    "Best voice actors", "Best villains played by actors", "Best Bond actors", "Best Batman actors",
    "Best Joker actors", "Best Spider-Man actors", "Best Doctor Who actors", "Best Hulk actors",
    "Most Oscar-nominated actors", "Best supporting actors", "Best child actors", "Best actors turned directors",
    "Best actors in dramas", "Best actors in thrillers", "Best actors in comedies", "Best actors in horror",
    "Most charismatic actors", "Most versatile actors", "Best actors who never won an Oscar", "Best character actors",
    "Best Disney actors", "Best Marvel actors", "Best Star Wars actors", "Best Harry Potter actors",
    "Best Lord of the Rings actors", "Best Hollywood legends", "Best Bollywood actors", "Most followed actors",

    // Actresses
    "Highest-paid actresses", "Best action actresses", "Best comedy actresses", "Best actresses today",
    "Best British actresses", "Best Indian actresses", "Best Korean actresses", "Best Oscar-winning actresses",
    "Best actresses of the 90s", "Best actresses of the 2000s", "Best actresses under 40", "Best voice actresses",
    "Best Bond girls", "Best Disney actresses", "Best Marvel actresses", "Best Harry Potter actresses",
    "Best Star Wars actresses", "Best actresses in dramas", "Best actresses in thrillers", "Best actresses in horror",
    "Most Oscar-nominated actresses", "Best supporting actresses", "Best child actresses", "Best actresses turned directors",
    "Best Hollywood legends actresses", "Best Bollywood actresses", "Most versatile actresses", "Best actresses who never won an Oscar",
    "Most followed actresses", "Best TV actresses", "Best sitcom actresses", "Best Netflix actresses",
    "Best actresses in rom-coms", "Best Wonder Woman actresses", "Best Batman villains actresses", "Best fantasy actresses",
    "Best sci-fi actresses", "Best period drama actresses", "Best actresses of the 70s", "Best actresses of the 80s",

    // Sports
    "Best football strikers ever", "Best football goalkeepers ever", "Best football midfielders ever", "Best football defenders ever",
    "Best football wingers ever", "Best Premier League players", "Best La Liga players", "Best Champions League players",
    "Best World Cup players", "Best World Cup goals", "Best World Cup teams", "Best football stadiums",
    "Best football rivalries", "Best Premier League clubs", "Best Barcelona players", "Best Real Madrid players",
    "Best Manchester United players", "Best Liverpool players", "Best Arsenal players", "Best Chelsea players",
    "Best Brazil players", "Best Argentina players", "Best German players", "Best Italian players",
    "Best French players", "Best English players", "Best NBA teams ever", "Best NBA centers",
    "Best NBA point guards", "Best NBA dunkers", "Best Lakers players", "Best Bulls players",
    "Best WNBA players", "Best NFL teams ever", "Best NFL running backs", "Best NFL wide receivers",
    "Best NHL players", "Best MLB pitchers", "Best MLB home run hitters", "Best cricketers of the 21st century",
    "Best Test batsmen", "Best fast bowlers", "Best spin bowlers", "Best IPL players",
    "Best cricket captains", "Best tennis rivalries", "Best Grand Slam winners", "Best Wimbledon champions",
    "Best female tennis players", "Best F1 teams", "Best F1 races", "Best MotoGP riders",
    "Best rally drivers", "Best cyclists in the Tour de France", "Best marathon runners", "Best Olympic gymnasts",
    "Best Olympic swimmers", "Best Olympic sprinters", "Best Winter Olympians", "Best skiers ever",
    "Best surfers ever", "Best skateboarders ever", "Best snooker players", "Best darts players",
    "Best table tennis players", "Best badminton players", "Best volleyball players", "Best rugby union players",
    "Best UFC fighters", "Best heavyweight boxers", "Best MMA fighters", "Best wrestlers in WWE",
    "Best martial artists", "Best esports teams", "Best Dota 2 players", "Best League of Legends players",
    "Best CS:GO players", "Best fighting game players", "Most expensive footballers", "Highest-paid athletes",
    "Most-watched sporting events", "Best sports mascots", "Best sports commentators",

    // General knowledge
    "Largest cities in Europe", "Largest cities in Asia", "Largest cities in Africa", "Largest countries by population",
    "Smallest countries", "Richest countries", "Most visited countries", "Most beautiful cities",
    "Best capital cities", "Best cities for food", "Longest bridges", "Longest tunnels",
    "Longest walls in history", "Oldest cities in the world", "Tallest waterfalls", "Biggest waterfalls",
    "Largest islands", "Largest volcanoes", "Deepest lakes", "Highest capital cities",
    "Largest rivers by flow", "Famous mountain ranges", "Best hiking trails", "Best ski resorts",
    "Best diving spots", "Best road trips", "Most iconic bridges", "Most famous castles",
    "Most famous palaces", "Most famous cathedrals", "Most famous temples", "Most famous towers",
    "Most famous paintings", "Most famous sculptures", "Most famous poets", "Most famous playwrights",
    "Most famous authors", "Best classic novels", "Best science fiction books", "Best mystery novels",
    "Best children's books", "Best graphic novels", "Best manga series", "Best comic book characters",
    "Most famous scientists", "Most famous mathematicians", "Most famous inventors", "Most famous physicists",
    "Most famous astronauts", "Most famous explorers", "Most famous queens", "Most famous kings",
    "Most famous presidents", "Most famous prime ministers", "Most famous revolutions", "Most famous wars",
    "Most famous pirates", "Most famous spies", "Most famous artists", "Most famous architects",
    "Most famous fashion designers", "Most famous chefs", "Most famous magicians", "Most famous photographers",
    "Most famous dancers", "Most famous singers", "Most famous bands", "Most famous DJs",
    "Most famous YouTubers", "Most famous streamers", "Most famous podcasters", "Most famous billionaires",
    "Most famous tech founders", "Most valuable brands", "Biggest tech companies", "Biggest car makers",
    "Biggest airlines", "Biggest banks", "Biggest oil companies", "Biggest toy brands",
    "Most popular websites", "Most popular apps", "Most popular mobile games", "Most popular social networks",
    "Most popular search engines", "Most popular operating systems", "Most popular web browsers", "Most popular game engines",
    "Best programming languages to learn", "Best laptops ever made", "Best video game graphics cards", "Best gaming headsets",
    "Best video game characters", "Best video game villains", "Best video game soundtracks", "Best indie games",
    "Best co-op games", "Best multiplayer games", "Best mobile games", "Best puzzle games",
    "Best platformers", "Best shooters", "Best survival games", "Best sandbox games",
    "Best sports video games", "Best Sonic games", "Best Minecraft mods", "Best Pokémon games",
    "Best Final Fantasy games", "Best Call of Duty games", "Best GTA games", "Best Assassin's Creed games",
    "Best Mortal Kombat characters", "Best Street Fighter characters", "Best Smash Bros characters", "Best Mario characters",
    "Most popular fruits", "Most popular vegetables", "Most popular spices", "Most popular pasta dishes",
    "Most popular cheeses", "Most popular teas", "Most popular cocktails", "Most popular beers",
    "Most popular wines", "Most popular snacks", "Most popular ice cream flavours", "Most popular fast foods",
    "Most popular pizzas", "Most popular burgers", "Best Indian dishes", "Best Italian dishes",
    "Best Japanese dishes", "Best Mexican dishes", "Best Chinese dishes", "Best Thai dishes",
    "Best Sri Lankan dishes", "Best desserts around the world", "Best breads", "Best sandwiches",
    "Best soups", "Best noodle dishes", "Best rice dishes", "Best chocolate bars",
    "Best candy brands", "Best cereals", "Best energy drinks", "Best sports drinks",
    "Most spoken languages in Europe", "Hardest languages to learn", "Easiest languages to learn", "Most common surnames",
    "Most common first names", "Longest words in English", "Most popular dog names", "Most expensive paintings",
    "Most expensive cars", "Most expensive watches", "Most expensive cities", "Cheapest countries to visit",
    "Most important inventions ever", "Most important discoveries", "Biggest scientific breakthroughs", "Biggest disasters in history",
    "Biggest earthquakes", "Biggest hurricanes", "Largest meteor impacts", "Brightest stars",
    "Biggest stars", "Largest moons", "Planets by size", "Most famous constellations",
    "Most famous space telescopes", "Most important space missions", "Most famous mathematicians ever", "Most famous equations",
    "Most famous paradoxes", "Most famous mysteries", "Most famous myths", "Greek gods",
    "Norse gods", "Egyptian gods", "Roman emperors", "Ancient wonders",
    "Most famous philosophers ever", "Most famous religious texts", "Largest religions", "Oldest universities",
    "Most famous museums", "Most famous libraries", "Most famous zoos"
];